/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

/**
 *
 * @author Danie
 */
public class Articulo extends javax.swing.JPanel {
    //VARIABLES
    String Producto;
    String Unidades;
    String Precio;
    String Total;
    
    //CONSTRUTORES
    public Articulo() {
        initComponents();
        DatosVacios();
    }

    public Articulo(String Producto, String Unidades, String Precio, String Total){
        initComponents();
        lblProducto.setText(Producto);
        lblUnidades.setText(Unidades);
        lblPrecio.setText(Longitud(Precio));
        lblTotal.setText(Longitud(Total));
    }
    
    private void DatosVacios(){        
        lblProducto.setText("");
        lblUnidades.setText("");
        lblPrecio.setText("");
        lblTotal.setText("");
    }
    
    private String Longitud(String Variable){
        String Aux = Variable.substring(Variable.length()-2,Variable.length());
        System.out.println(Aux);
        if(Aux.equals(".0")) Variable=Variable+"0";
        return Variable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUnidades = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUnidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUnidades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUnidades.setText("000");
        add(lblUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 30, -1));

        lblProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProducto.setText("000");
        add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, -1));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio.setText("000");
        add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 60, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("000");
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnidades;
    // End of variables declaration//GEN-END:variables
}
