/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Metodos_sql;
import static Clases.Metodos_sql.conexion;
import static Clases.Metodos_sql.st;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author lpzkn
 */
public class Restablecer_Password extends javax.swing.JFrame {

    /**
     * Creates new form Restablecer_Password
     */
    public Restablecer_Password() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
Connection conn = conexion.conectar();
    Metodos_sql metodos = new Metodos_sql();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtxtUsuario = new javax.swing.JTextField();
        JtxtPassword = new javax.swing.JTextField();
        JtxtNewPassword = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        txtNewContraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsuario.setText("Usuario");

        txtNewContraseña.setText("Nueva Contraseña");

        txtPassword.setText("Contraseña");

        jLabel1.setText("Actualizar Contraseña");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtPassword)
                    .addComponent(txtNewContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JtxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(JtxtUsuario))
                    .addComponent(JtxtNewPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewContraseña))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //Verificacion del usuario existente y si su contraseña es igual a la actual
        actualizarContraseña();
        
    }//GEN-LAST:event_jLabel1MouseClicked
    public void actualizarContraseña() {
    String usuario = JtxtUsuario.getText();
    String contraseñaActual = JtxtPassword.getText();
    String nuevaContraseña = JtxtNewPassword.getText();

    // Verificar la contraseña actual
    if (verificarContraseña()==true) {
        try {
            String sql = "UPDATE Usuario SET contraseña = ? WHERE Usuario = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nuevaContraseña);
            pst.setString(2, usuario);

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Contraseña actualizada exitosamente");
                 Login v = new Login();
                 v.setVisible(true);
                 this.dispose();   
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la contraseña");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar la contraseña: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "La contraseña actual o el usuario es incorrecto");
    }
}
    
public boolean verificarContraseña() {
    try {
        String usuario = JtxtUsuario.getText(); // Obtener usuario de la caja de texto
        String contraseña = JtxtPassword.getText(); // Obtener contraseña actual de la caja de texto

        String sql = "SELECT * FROM Usuario WHERE Usuario = ? AND contraseña = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, usuario);
        pst.setString(2, contraseña);

        ResultSet rs = pst.executeQuery();

        return rs.next(); // Si encuentra un registro, la contraseña es correcta
    } catch (Exception e) {
        e.printStackTrace();
        //JOptionPane.showMessageDialog(null, "Error al verificar la contraseña: " + e.getMessage());
        return false; // Error al verificar la contraseña
    }
}

     public void registrar2(){

        try
        {            
            JOptionPane.showMessageDialog(null, "Contraseña restablecida");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "error al guardar" + e.getMessage());
        }
        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restablecer_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restablecer_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restablecer_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restablecer_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restablecer_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtNewPassword;
    private javax.swing.JTextField JtxtPassword;
    private javax.swing.JTextField JtxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtNewContraseña;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
