/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;

/**
 *
 * @author Danie
 */
public class Ticket extends javax.swing.JFrame {

    int click = 0;
    ConexionBD conexion = new ConexionBD();
    Connection conn;
    
    public Ticket() {
        initComponents();
        pnlProductos.setLayout(new BoxLayout(pnlProductos, BoxLayout.Y_AXIS));
        lblFecha.setText(fechaSistema());
        lblHora.setText(Hora());
        btnNuevo.setVisible(false);
    }
    
    public Ticket(String Usuario, String Total, String Pago, String Cambio, String idVenta) {
        initComponents();
        pnlProductos.setLayout(new BoxLayout(pnlProductos, BoxLayout.Y_AXIS));
        lblUsuario.setText(Usuario);
        lblTotal.setText(Total);
        lblPago.setText(Pago);
        lblCambio.setText(Cambio);
        lblFecha.setText(fechaSistema());
        lblHora.setText(Hora());
        lblVenta.setText(idVenta);
        btnNuevo.setVisible(false);
    }
    
    private String fechaSistema(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String fechaLlegada = (dtf.format(LocalDateTime.now()));
        return fechaLlegada;
    }
    
    private String Hora(){
        return new SimpleDateFormat("HH:mm").format(Calendar.getInstance().getTime());
    }
    
    private void rellenar(){
        int cont=20;
        for(int i=0; i<cont; i++){
            if(i<click){
                pnlProductos.add(new Articulo("Picafresa","2","50.0","100.0"));
            }else{
                pnlProductos.add(new Articulo());
            }
        }
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblVenta = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTicket.setBackground(new java.awt.Color(255, 255, 255));
        pnlTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("===================================================");
        pnlTicket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, -1));

        jLabel2.setText("===================================================");
        pnlTicket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, -1));

        jLabel3.setText("===================================================");
        pnlTicket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 360, 20));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("*usuario*");
        pnlTicket.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" \" EL TREBOL \"");
        pnlTicket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, -1));

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHora.setText("00:00");
        pnlTicket.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Atendido por:");
        pnlTicket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(" Cambio:");
        pnlTicket.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 60, -1));

        lblVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVenta.setText("*num*");
        pnlTicket.add(lblVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha.setText("00/00/0000");
        pnlTicket.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, -1));

        jLabel11.setText("===================================================");
        pnlTicket.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        pnlProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProductos.setLayout(new javax.swing.BoxLayout(pnlProductos, javax.swing.BoxLayout.LINE_AXIS));
        pnlTicket.add(pnlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 360, 350));

        jLabel12.setText("===================================================");
        pnlTicket.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 360, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Subtotal");
        pnlTicket.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 120, 60, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Total:");
        pnlTicket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Pago:");
        pnlTicket.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 40, -1));

        lblCambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCambio.setText("$00.00");
        pnlTicket.add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 80, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("$00.00");
        pnlTicket.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 80, -1));

        lblPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPago.setText("$00.00");
        pnlTicket.add(lblPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Venta:");
        pnlTicket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Producto");
        pnlTicket.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 60, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Unidades");
        pnlTicket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Precio");
        pnlTicket.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 60, -1));

        btnNuevo.setText("jButton1");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        pnlTicket.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        getContentPane().add(pnlTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        click++;
        pnlProductos.removeAll();
        this.validate();
        this.repaint();
        rellenar();
    }//GEN-LAST:event_btnNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVenta;
    public javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlTicket;
    // End of variables declaration//GEN-END:variables
}
